name: instagram_share
description: Flutter plugin allowing to share media to Instagram by using native mechanisms
version: 0.1.8
homepage: https://github.com/JEuler/instagram_share

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cloverrepublic.com.instagramshare
        pluginClass: InstagramSharePlugin
