name: instagram_share
description: Flutter plugin allowing to share media to Instagram by using native mechanisms
version: 0.2.1
homepage: https://github.com/JEuler/instagram_share

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cloverrepublic.com.instagramshare
        pluginClass: InstagramSharePlugin
        dartPluginClass: InstagramShare
      ios:
        pluginClass: InstagramsharePlugin
