name: instagram_share
description: Flutter plugin allowing to share media to Instagram by using native mechanisms
version: 0.1.5
homepage: https://github.com/JEuler/instagram_share

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Launcher used for ios
  url_launcher: ^5.4.2
  # Image downloader for gallery savings
  image_downloader: ^0.19.2
  # Permissions handler
  permission_handler: ^5.0.0+hotfix.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cloverrepublic.com.instagramshare
    pluginClass: InstagramSharePlugin
